name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true
          cache: false

      - name: Initialize Go module
        run: |
          if [ ! -f go.mod ]; then
            go mod init fusion
          fi
          go mod tidy

      - name: Check code
        run: |
          go vet ./...
          go fmt ./...

      - name: Build
        run: |
          VERSION=$(date +'%Y%m%d%H%M')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          go build -v -ldflags="-X 'main.Version=$VERSION'" -o fusion ./...

      - name: Test
        run: go test -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fusion:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fusion:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}